/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package google;

/**
 *
 * @author hocvien
 */
public class Form2 extends javax.swing.JFrame {

    public CSDL csdl =new CSDL();
    public String pass;
    public String email;
    public String hoTen;

    public Form2(String pass, String email, String hoTen) {
        this.pass = pass;
        this.email = email;
        this.hoTen = hoTen;
        initComponents();
        this.setLocationRelativeTo(null);        
    }


    
    /**
     * Creates new form Form1
     */
    public Form2() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel_TBGmail2 = new javax.swing.JLabel();
        jTextField_ngay = new javax.swing.JTextField();
        jTextField_nam = new javax.swing.JTextField();
        jTextField_sdt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_ngayTB = new javax.swing.JLabel();
        jLabel_namTB = new javax.swing.JLabel();
        jLabel_tenNDTB = new javax.swing.JLabel();
        jLabel_emailTB = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jComboBox_thang = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Chào Mừng Bạn Đến Với Google");

        jLabel_TBGmail2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_TBGmail2.setText("Tiếp Tục Với Gmail");

        jTextField_ngay.setText("Ngày");
        jTextField_ngay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ngayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_ngayFocusLost(evt);
            }
        });
        jTextField_ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ngayActionPerformed(evt);
            }
        });
        jTextField_ngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ngayKeyReleased(evt);
            }
        });

        jTextField_nam.setText("Năm");
        jTextField_nam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_namFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_namFocusLost(evt);
            }
        });
        jTextField_nam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_namKeyReleased(evt);
            }
        });

        jTextField_sdt.setText("Số Điện Thoại (Tùy Chọn)");
        jTextField_sdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_sdtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_sdtFocusLost(evt);
            }
        });

        jButton1.setText("Tiếp Theo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_email.setText("Email (Tùy Chọn)");
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });

        jComboBox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Không Muốn Trả Lời" }));

        jLabel5.setText("Giới Tính");

        jLabel7.setText("Ngày Sinh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TBGmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jTextField_ngay)
                                    .addComponent(jLabel_ngayTB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_namTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_nam, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel_tenNDTB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_emailTB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_TBGmail2)
                .addGap(11, 11, 11)
                .addComponent(jTextField_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_tenNDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_emailTB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_namTB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ngayTB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ngayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ngayFocusGained
        if(jTextField_ngay.getText().equals("Ngày")){
            jTextField_ngay.setText("");
        }       
    }//GEN-LAST:event_jTextField_ngayFocusGained

    private void jTextField_sdtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_sdtFocusGained
        if(jTextField_sdt.getText().equals("Số Điện Thoại (Tùy Chọn)")){
            jTextField_sdt.setText("");
        }
    }//GEN-LAST:event_jTextField_sdtFocusGained

    private void jTextField_sdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_sdtFocusLost
         if(jTextField_sdt.getText().equals("")){
            jTextField_sdt.setText("Số Điện Thoại (Tùy Chọn)");
        }
    }//GEN-LAST:event_jTextField_sdtFocusLost

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
          if(jTextField_email.getText().equals("Email (Tùy Chọn)")){
            jTextField_email.setText("");
        }
        
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
          if(jTextField_email.getText().equals("")){
            jTextField_email.setText("Email (Tùy Chọn)");
        }
    }//GEN-LAST:event_jTextField_emailFocusLost

    private void jTextField_ngayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ngayFocusLost
        if(jTextField_ngay.getText().equals("")){
            jTextField_ngay.setText("Ngày");
        } 
    }//GEN-LAST:event_jTextField_ngayFocusLost

    private void jTextField_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ngayActionPerformed

    private void jTextField_namFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_namFocusGained
        if(jTextField_nam.getText().equals("Năm")){
            jTextField_nam.setText("");
        } 
        
    }//GEN-LAST:event_jTextField_namFocusGained

    private void jTextField_namFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_namFocusLost
        if(jTextField_nam.getText().equals("")){
            jTextField_nam.setText("Năm");
        }       
    }//GEN-LAST:event_jTextField_namFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ngay =0, nam =0;
        if(jTextField_nam.getText().equals("Năm")){
            jLabel_namTB.setText("Năm Không Rỗng");
        }
        else{
            nam =1;
            jLabel_namTB.setText("");
        }
        if(jTextField_ngay.getText().equals("Ngày")){
            jLabel_ngayTB.setText("Năm Không Rỗng");
        }
        else{
            ngay =1;
            jLabel_ngayTB.setText("");
        }
        if(ngay == 1 && nam ==1){
            // khong lấy đc du lieu thu form 1
            System.out.println(hoTen +" " + email +" "+ pass);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_namKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_namKeyReleased
        if(jTextField_nam.getText().equals("Năm")){
            jLabel_namTB.setText("Năm Không Rỗng");
        }
        else{
            jLabel_namTB.setText("");
        }
    }//GEN-LAST:event_jTextField_namKeyReleased

    private void jTextField_ngayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ngayKeyReleased
        if(jTextField_ngay.getText().equals("Ngày")){
            jLabel_ngayTB.setText("Năm Không Rỗng");
        }
        else{
            jLabel_ngayTB.setText("");
        }
    }//GEN-LAST:event_jTextField_ngayKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Form2().setVisible(true);
                Form1 form1 = new Form1();
                form1.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_thang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_TBGmail2;
    private javax.swing.JLabel jLabel_emailTB;
    private javax.swing.JLabel jLabel_namTB;
    private javax.swing.JLabel jLabel_ngayTB;
    private javax.swing.JLabel jLabel_tenNDTB;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nam;
    private javax.swing.JTextField jTextField_ngay;
    private javax.swing.JTextField jTextField_sdt;
    // End of variables declaration//GEN-END:variables
}
